//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Rational.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using System;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class RationalLexer : Lexer {
	public const int
		T__0=1, T__1=2, T__2=3, INT=4, MUL=5, DIV=6, ADD=7, SUB=8, WS=9;
	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "INT", "MUL", "DIV", "ADD", "SUB", "WS"
	};


	public RationalLexer(ICharStream input)
		: base(input)
	{
		Interpreter = new LexerATNSimulator(this,_ATN);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "','", null, "'*'", "'/'", "'+'", "'-'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, "INT", "MUL", "DIV", "ADD", "SUB", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Rational.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public static readonly string _serializedATN =
		"\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x2\v/\b\x1\x4\x2\t"+
		"\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t"+
		"\t\t\x4\n\t\n\x3\x2\x3\x2\x3\x3\x3\x3\x3\x4\x3\x4\x3\x5\x6\x5\x1D\n\x5"+
		"\r\x5\xE\x5\x1E\x3\x6\x3\x6\x3\a\x3\a\x3\b\x3\b\x3\t\x3\t\x3\n\x6\n*\n"+
		"\n\r\n\xE\n+\x3\n\x3\n\x2\x2\v\x3\x3\x5\x4\a\x5\t\x6\v\a\r\b\xF\t\x11"+
		"\n\x13\v\x3\x2\x4\x3\x2\x32;\x5\x2\v\f\xF\xF\"\"\x30\x2\x3\x3\x2\x2\x2"+
		"\x2\x5\x3\x2\x2\x2\x2\a\x3\x2\x2\x2\x2\t\x3\x2\x2\x2\x2\v\x3\x2\x2\x2"+
		"\x2\r\x3\x2\x2\x2\x2\xF\x3\x2\x2\x2\x2\x11\x3\x2\x2\x2\x2\x13\x3\x2\x2"+
		"\x2\x3\x15\x3\x2\x2\x2\x5\x17\x3\x2\x2\x2\a\x19\x3\x2\x2\x2\t\x1C\x3\x2"+
		"\x2\x2\v \x3\x2\x2\x2\r\"\x3\x2\x2\x2\xF$\x3\x2\x2\x2\x11&\x3\x2\x2\x2"+
		"\x13)\x3\x2\x2\x2\x15\x16\a*\x2\x2\x16\x4\x3\x2\x2\x2\x17\x18\a+\x2\x2"+
		"\x18\x6\x3\x2\x2\x2\x19\x1A\a.\x2\x2\x1A\b\x3\x2\x2\x2\x1B\x1D\t\x2\x2"+
		"\x2\x1C\x1B\x3\x2\x2\x2\x1D\x1E\x3\x2\x2\x2\x1E\x1C\x3\x2\x2\x2\x1E\x1F"+
		"\x3\x2\x2\x2\x1F\n\x3\x2\x2\x2 !\a,\x2\x2!\f\x3\x2\x2\x2\"#\a\x31\x2\x2"+
		"#\xE\x3\x2\x2\x2$%\a-\x2\x2%\x10\x3\x2\x2\x2&\'\a/\x2\x2\'\x12\x3\x2\x2"+
		"\x2(*\t\x3\x2\x2)(\x3\x2\x2\x2*+\x3\x2\x2\x2+)\x3\x2\x2\x2+,\x3\x2\x2"+
		"\x2,-\x3\x2\x2\x2-.\b\n\x2\x2.\x14\x3\x2\x2\x2\x5\x2\x1E+\x3\b\x2\x2";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
