
// This file has been generated by the GUI designer. Do not modify.
namespace MathObjects.UI.Stack
{
	public partial class StackButtonWidget
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button buttonPush;
		
		private global::Gtk.Button buttonPop;
		
		private global::Gtk.Button buttonClear;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MathObjects.UI.Stack.StackButtonWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MathObjects.UI.Stack.StackButtonWidget";
			// Container child MathObjects.UI.Stack.StackButtonWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonPush = new global::Gtk.Button ();
			this.buttonPush.CanFocus = true;
			this.buttonPush.Name = "buttonPush";
			this.buttonPush.UseUnderline = true;
			this.buttonPush.Label = global::Mono.Unix.Catalog.GetString ("Push");
			this.hbox1.Add (this.buttonPush);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonPush]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonPop = new global::Gtk.Button ();
			this.buttonPop.CanFocus = true;
			this.buttonPop.Name = "buttonPop";
			this.buttonPop.UseUnderline = true;
			this.buttonPop.Label = global::Mono.Unix.Catalog.GetString ("Pop");
			this.hbox1.Add (this.buttonPop);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonPop]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonClear = new global::Gtk.Button ();
			this.buttonClear.CanFocus = true;
			this.buttonClear.Name = "buttonClear";
			this.buttonClear.UseUnderline = true;
			this.buttonClear.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			this.hbox1.Add (this.buttonClear);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonClear]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonPush.Clicked += new global::System.EventHandler (this.OnButtonPushClicked);
			this.buttonPop.Clicked += new global::System.EventHandler (this.OnButtonPopClicked);
			this.buttonClear.Clicked += new global::System.EventHandler (this.OnButtonClearClicked);
		}
	}
}
