
// This file has been generated by the GUI designer. Do not modify.
namespace MathObjects.UI.Stack
{
	public partial class StackButtonWidget
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Button buttonPop;
		
		private global::Gtk.Button buttonClear;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MathObjects.UI.Stack.StackButtonWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MathObjects.UI.Stack.StackButtonWidget";
			// Container child MathObjects.UI.Stack.StackButtonWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(5));
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonPop = new global::Gtk.Button ();
			this.buttonPop.Name = "buttonPop";
			this.buttonPop.UseUnderline = true;
			this.buttonPop.Label = global::Mono.Unix.Catalog.GetString ("Pop");
			this.vbox2.Add (this.buttonPop);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.buttonPop]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonClear = new global::Gtk.Button ();
			this.buttonClear.Name = "buttonClear";
			this.buttonClear.UseUnderline = true;
			this.buttonClear.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			this.vbox2.Add (this.buttonClear);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.buttonClear]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonPop.Clicked += new global::System.EventHandler (this.OnButtonPopClicked);
			this.buttonClear.Clicked += new global::System.EventHandler (this.OnButtonClearClicked);
		}
	}
}
