
// This file has been generated by the GUI designer. Do not modify.
namespace MathObjects.UI.Stack
{
	public partial class InputWidget
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.TextView textview1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MathObjects.UI.Stack.InputWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MathObjects.UI.Stack.InputWidget";
			// Container child MathObjects.UI.Stack.InputWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(2));
			this.textview1.LeftMargin = 3;
			this.vbox1.Add (this.textview1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.textview1]));
			w1.Position = 0;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
