
// This file has been generated by the GUI designer. Do not modify.
namespace MathObjects.UI.Stack
{
	public partial class InputWidget
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Entry entry1;
		
		private global::MathObjects.UI.Stack.StackButtonWidget stackbuttonwidget1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MathObjects.UI.Stack.InputWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MathObjects.UI.Stack.InputWidget";
			// Container child MathObjects.UI.Stack.InputWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.hbox1.Add (this.entry1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry1]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.stackbuttonwidget1 = new global::MathObjects.UI.Stack.StackButtonWidget ();
			this.stackbuttonwidget1.Events = ((global::Gdk.EventMask)(256));
			this.stackbuttonwidget1.Name = "stackbuttonwidget1";
			this.hbox1.Add (this.stackbuttonwidget1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.stackbuttonwidget1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
