
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::MathObjects.UI.FieldWidget fieldwidget1;
	
	private global::MathObjects.UI.Input.InputWidget inputwidget1;
	
	private global::MathObjects.UI.Stack.StackWidget2 stackwidget21;
	
	private global::MathObjects.UI.Widgets.MathObjetsWidget mathobjetswidget1;
	
	private global::MathObjects.UI.Widgets.MathOperationsWidget mathoperationswidget1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fieldwidget1 = new global::MathObjects.UI.FieldWidget ();
		this.fieldwidget1.Events = ((global::Gdk.EventMask)(256));
		this.fieldwidget1.Name = "fieldwidget1";
		this.vbox1.Add (this.fieldwidget1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fieldwidget1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.inputwidget1 = new global::MathObjects.UI.Input.InputWidget ();
		this.inputwidget1.Events = ((global::Gdk.EventMask)(256));
		this.inputwidget1.Name = "inputwidget1";
		this.vbox1.Add (this.inputwidget1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.inputwidget1]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.stackwidget21 = new global::MathObjects.UI.Stack.StackWidget2 ();
		this.stackwidget21.Events = ((global::Gdk.EventMask)(256));
		this.stackwidget21.Name = "stackwidget21";
		this.vbox1.Add (this.stackwidget21);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.stackwidget21]));
		w3.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.mathobjetswidget1 = new global::MathObjects.UI.Widgets.MathObjetsWidget ();
		this.mathobjetswidget1.Events = ((global::Gdk.EventMask)(256));
		this.mathobjetswidget1.Name = "mathobjetswidget1";
		this.vbox1.Add (this.mathobjetswidget1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.mathobjetswidget1]));
		w4.Position = 3;
		// Container child vbox1.Gtk.Box+BoxChild
		this.mathoperationswidget1 = new global::MathObjects.UI.Widgets.MathOperationsWidget ();
		this.mathoperationswidget1.Events = ((global::Gdk.EventMask)(256));
		this.mathoperationswidget1.Name = "mathoperationswidget1";
		this.vbox1.Add (this.mathoperationswidget1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.mathoperationswidget1]));
		w5.Position = 4;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 411;
		this.DefaultHeight = 433;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
