
// This file has been generated by the GUI designer. Do not modify.
namespace MathObjects.UI
{
	public partial class FieldWidget
	{
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.ComboBox combobox1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MathObjects.UI.FieldWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MathObjects.UI.FieldWidget";
			// Container child MathObjects.UI.FieldWidget.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.BorderWidth = ((uint)(4));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.Name = "combobox1";
			this.alignment1.Add (this.combobox1);
			this.Add (this.alignment1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
