
// This file has been generated by the GUI designer. Do not modify.
namespace MathObjects.UI
{
	public partial class EnterWidget
	{
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.Button button2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MathObjects.UI.EnterWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MathObjects.UI.EnterWidget";
			// Container child MathObjects.UI.EnterWidget.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Enter");
			this.alignment1.Add (this.button2);
			this.Add (this.alignment1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
