
// This file has been generated by the GUI designer. Do not modify.
namespace MathObjects.UI.Widgets
{
	public partial class MathObjetsWidget
	{
		private global::Gtk.Table table1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MathObjects.UI.Widgets.MathObjetsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MathObjects.UI.Widgets.MathObjetsWidget";
			// Container child MathObjects.UI.Widgets.MathObjetsWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
